owncloud-docker/server

README.md

@felixboehm plz review and merge.

Added hint how to access the owncloud installation in browser

---

.drone.yml

Run smoke tests

---

.drone.yml

I hope this is all to do to upgrade the container.

release-10.2.0

---

.drone.yml

Publish the 10.3.0alpha2 for testing.

Release 10.3.0alpha2

---

.drone.yml

- Changelog https://github.com/owncloud/core/blob/v10.3.0RC1/CHANGELOG.md

Release 10.3.0RC1

---

.drone.star

- 10.3.2
- 10.3.2-rc1
- 10.3.1
- latest (now 10.3.2)
- 10.3
- 10

Release 10.3.2

---

.drone.star

Add version entry `10.4.0-rc2`
This obsoletes https://github.com/owncloud-docker/server/pull/165

Release 10.4.0 rc2

---

.drone.star

Handbook mentions a testing branch for RCs, but there is none. We now do all in master, correct?
Should we tag master with 'v10.3.2' before we merge?

Add a version section for '10.4.0-rc1'

---

.drone.star

release 10.4.0RC3

---

.drone.star

On top of PR #181 which fixes the existing pipelines.

Add pipeline for 10.4.1RC1

---

.drone.star
CHANGELOG.md
README.md
v18.04/Dockerfile.amd64
v20.04/Dockerfile.amd64
v20.04/Dockerfile.arm32v7
v20.04/Dockerfile.arm64v8
v20.04/manifest.tmpl

Add 10.5.0beta1 with tag 10.5
The tag latest remains at 10.4.1 while 10.5 is prerelease

10.5.0beta1 with ubuntu 20.04

---

.drone.star
v18.04/Dockerfile.amd64

Notes:
- the grace period popup should be disabled by default in all acceptance tests now, so that extra commit should no longer be needed here.
- maybe the "disable theme-enterprise" commit is also no longer needed?

Release 10.5.0 RC4

---

.drone.star

Docker for https://github.com/owncloud/enterprise/issues/4020#issuecomment-661209489

release 10.5.0RC5

---

.drone.star

for https://github.com/owncloud/enterprise/issues/4020#issuecomment-663022748

release 10.5.0RC6

---

.drone.star

Items to double check:
- should ldap point to github or marketplace?
- which qa tarball should be used - owncloud-complete-20200731-qa.tar.bz2 or owncloud-10.5.0-qa.tar.bz2?

Release 10.5.0

---

.drone.star

and .. I still have doubts about the commands listing destroying the CMD from dockerfile...

apply disable integrity config snippet to both ui and api

---

.drone.star

release 10.6.0 rc1

---

.drone.star

Release 10.6.0 rc3

---

.drone.star

for https://github.com/owncloud/enterprise/issues/4238
This updates 10.6.0 only, 
I'll update the `latest` tag too, when the smoke tests are done.

release 10.6.0

---

.drone.star

for https://github.com/owncloud/enterprise/issues/4449

release 10.7.0 beta2

---

.drone.star

Mirrors are ready for this in 45min.

Release 10.7.0-rc1

---

.drone.star

release 10.8.0

---

.drone.star

Added "10.9.0-beta1" to .drone.star

release 10.9.0 beta1

---

.drone.star

10.9.0 rc1

---

.drone.star

Update to 10.9.0 final

---

.drone.star

Add 10.9.1RC1

---

.drone.star

merge after 17:05 today, when mirrors have the complete image :-)

add add-10-9-1-rc2

---

.drone.star
.trivyignore
README.md

10.10.0-rc1 is complete-20220504

release 10.10.0 rc1

---

.drone.star

final RC, most likely.
translation updates, config.sample.php updates, wnd updated to 2.1.1, updated Log filtering.

Prepare RC3

---

.drone.star

To be merged Thursday 2022-05-19, evening.

[Draft: Do not merge yet] Prepare 10.10.0 final

---

.drone.star

... and later tonight we'll have the final!

bump 10.11.0 from rc.1 to rc.2

---

.drone.star
README.md

Final 10.12.0 -- version.php updated, otherwise same code as 10.12.0-rc3

release 10.12.0 complete as docker image

---

.drone.star
README.md

Keeping exactly only the last two minor versions

Update 10.12.0 to 10.12.1

---

.drone.star
README.md

(removing 10.12.1 and 10.12.2-rc.1, keeping 10.11.0)

update drone.star to final 10.12.2

---

.drone.star

Add release candidate 1 for core 10.13.0 to the docker config.

Release 10.13.0-rc.1

---

.drone.star

Adding drawio-1.0.1,
fixing ie11 compatibitlity
and re-re-re-fixing heic

ADD 10.13.0.RC 2

---

.drone.star
README.md

add 10.13.0, drop 10.11.0

---

.drone.star
README.md

Merge in 20 min, when the mirror sync is done.

Added 10.13.1 (removing its RC)

---

v20.04/Dockerfile.amd64
v20.04/Dockerfile.arm64v8

Fixes: https://github.com/owncloud-docker/server/issues/425
This reverts commit a95e5259831522418b3450eef717710b77504b51.

Revert "chore: cleanup testfiles from apps and lib (#424)"

---

.drone.star
README.md

First release candidate of 10.14.0

add 10.14.0-rc.1

---

.drone.star
README.md

add 10.15.0-rc.1

---

.drone.star
README.md

rc.4 should fix the trivy issues seen yesterday with rc.3

Add 10.15.0 rc.4
